// <auto-generated />
using System;
using ApiEmpresas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEmpresas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207203014_AdicionandoNovaPropriedadeEmFuncionario")]
    partial class AdicionandoNovaPropriedadeEmFuncionario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiEmpresas.Models.EmpresaSetor", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("EmpresaId", "SetorId");

                    b.HasIndex("SetorId");

                    b.ToTable("EmpresaSetores");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApiEmpresas.Models.Profissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Profissoes");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("FuncionarioSetor", b =>
                {
                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("FuncionarioId", "SetorId");

                    b.HasIndex("SetorId");

                    b.ToTable("FuncionarioSetor");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Empresa", b =>
                {
                    b.HasBaseType("ApiEmpresas.Models.Pessoa");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("int");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("ApiEmpresas.Models.Funcionario", b =>
                {
                    b.HasBaseType("ApiEmpresas.Models.Pessoa");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProfissaoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(65,30)");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProfissaoId");

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("ApiEmpresas.Models.EmpresaSetor", b =>
                {
                    b.HasOne("ApiEmpresas.Models.Empresa", "Empresa")
                        .WithMany("Setores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEmpresas.Models.Setor", "Setor")
                        .WithMany("Empresas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Pessoa", b =>
                {
                    b.OwnsOne("ApiEmpresas.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiEmpresas.Models.Profissao", b =>
                {
                    b.HasOne("ApiEmpresas.Models.Setor", null)
                        .WithMany("Profissoes")
                        .HasForeignKey("SetorId");
                });

            modelBuilder.Entity("FuncionarioSetor", b =>
                {
                    b.HasOne("ApiEmpresas.Models.Funcionario", "Funcionario")
                        .WithMany("Setores")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEmpresas.Models.Setor", "Setor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Empresa", b =>
                {
                    b.HasOne("ApiEmpresas.Models.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("ApiEmpresas.Models.Empresa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiEmpresas.Models.Funcionario", b =>
                {
                    b.HasOne("ApiEmpresas.Models.Empresa", "Empresa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiEmpresas.Models.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("ApiEmpresas.Models.Funcionario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEmpresas.Models.Profissao", "Profissao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("ProfissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Profissao");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Profissao", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Setor", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Funcionarios");

                    b.Navigation("Profissoes");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Empresa", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Setores");
                });

            modelBuilder.Entity("ApiEmpresas.Models.Funcionario", b =>
                {
                    b.Navigation("Setores");
                });
#pragma warning restore 612, 618
        }
    }
}
